#端口号
server:
  port: 9090

spring:
  # 应用名称
  application:
    # 万事屋商城（主要做秒杀）
    name: seckill-mall
  thymeleaf:
    # 关闭thymeleaf缓存
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 连接池名称
      pool-name: mallCP
      # 空闲连接最大存活时间,默认10分钟-600000
      idle-timeout: 1800000
      # 最小连接数
      minimum-idle: 5
      # 测试连接是否可以的查询语句
      connection-test-query: select 1
  # redis配置
  redis:
    # ip
    host: 192.168.137.66
    # 端口号
    port: 6379
    # 密码
    password: root
    # 数据库
    database: 0
    # 连接池配置
    lettuce:
      pool:
        # 最大连接数， 默认8
        max-active: 1000
        # 最长等待时间
        max-wait: 5000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5



# mybatis-plus配置
mybatis-plus:
  # mapper文件位置
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 起别名
  type-aliases-package: com.huajframe.seckill.entity
  # 字段名对属性名
  configuration:
    map-underscore-to-camel-case: true

# sql打印级别
logging:
  level:
    com:
      huajframe:
        seckill:
          dao: debug
